/**
 * Compile Error Sample
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { DefaultServiceInterface }                            from './default.serviceInterface';


@Injectable({
  providedIn: 'root'
})
export class DefaultService implements DefaultServiceInterface {

    protected basePath = 'http://localhost:9090/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * @param version 
     * @param tenantCode 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSampleDataWithAdditionalProperties(version: string, tenantCode: string, observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: Array<SampleSchema>; }>;
    public getSampleDataWithAdditionalProperties(version: string, tenantCode: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: Array<SampleSchema>; }>>;
    public getSampleDataWithAdditionalProperties(version: string, tenantCode: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: Array<SampleSchema>; }>>;
    public getSampleDataWithAdditionalProperties(version: string, tenantCode: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (version === null || version === undefined) {
            throw new Error('Required parameter version was null or undefined when calling getSampleDataWithAdditionalProperties.');
        }
        if (tenantCode === null || tenantCode === undefined) {
            throw new Error('Required parameter tenantCode was null or undefined when calling getSampleDataWithAdditionalProperties.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            '*/*',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<{ [key: string]: Array<SampleSchema>; }>(`${this.configuration.basePath}/endpoint/${encodeURIComponent(String(version))}/${encodeURIComponent(String(tenantCode))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
